name: Challenge 3 - Dynamic Config Generator

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  run_challenge_3:
    runs-on: ubuntu-latest

    env:
      TERRAFORM_VERSION: 1.5.7
      TERRAFORM_DIR: ./shared/terraform-challenges-23/challenge-3-service-generator

    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_DIR }}

    steps:
      - name: ğŸ“¥ Checkout cÃ³digo
        uses: actions/checkout@v4

      - name: â¬ Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: ğŸ“¦ Init
        run: terraform init

      - name: âœ… Validate
        run: terraform validate

      - name: ğŸš€ Plan
        run: terraform plan

      - name: ğŸ§¾ Ver archivos generados
        run: |
          echo "Archivos generados en carpeta 'services/'"
          ls -la services || echo "âš ï¸ No se generaron archivos"

      - name: ğŸ“¤ Subir servicios
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: services
          path: |
            ${{ env.TERRAFORM_DIR }}/services/*
          if-no-files-found: ignore
