name: Challenge 2 - Multi-Environment Generator

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      action:
        description: "AcciÃ³n a ejecutar (plan o apply)"
        required: true
        default: "plan"
      ref:
        description: "Rama o tag (opcional)"
        required: false
        default: "develop"

jobs:
  terraform_challenge_2:
    runs-on: ubuntu-latest

    env:
      TERRAFORM_VERSION: 1.12.2
      TERRAFORM_DIR: ./shared/terraform-challenges/challenge-2-multi-env

    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_DIR }}

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref_name }}

      - name: ğŸ› ï¸ Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: ğŸ“¦ Inicializar Terraform
        run: terraform init

      - name: âœ… Validar configuraciÃ³n
        run: terraform validate

      - name: ğŸš€ Ejecutar plan o apply
        run: |
          ACTION="${{ github.event.inputs.action || 'plan' }}"
          echo "ğŸ” AcciÃ³n seleccionada: $ACTION"
          if [ "$ACTION" = "apply" ]; then
            terraform apply -auto-approve
          else
            terraform plan
          fi

      - name: ğŸ“„ Mostrar archivos generados
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          echo "ğŸ“‚ Archivos generados:"
          ls -l ./outputs || echo "âš ï¸ No se encontraron archivos"

      - name: ğŸ“¦ Subir artefactos generados
        if: ${{ github.event.inputs.action == 'apply' && success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Environment_Templates
          path: |
            ${{ env.TERRAFORM_DIR }}/outputs/*
          if-no-files-found: ignore

  notify_slack_discord:
    needs: terraform_challenge_2
    if: always()
    uses: ./.github/workflows/notify_all.yml # Nombre del job
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    with:
      status: ${{ needs.terraform_challenge_2.result }} # Nombre del Job
      branch: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      repo: ${{ github.event.repository.name }}
      sha: ${{ github.sha }}
      pr_number: ${{ github.event.pull_request.number || '' }}
      commit_message: ${{ github.event.head_commit.message || '' }}
