name: Challenge 1 - Multi-Ambiente Config Generator

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  run_challenge_1:
    runs-on: ubuntu-latest

    env:
      TERRAFORM_VERSION: 1.5.7
      TERRAFORM_DIR: ./shared/terraform-challenges-23/challenge-1-multi-env

    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_DIR }}

    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v4

      - name: â¬ Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: ğŸ“¦ Init Terraform
        run: terraform init

      - name: âœ… Validate
        run: terraform validate

      - name: ğŸš€ Plan
        run: terraform plan

      - name: ğŸ“ Apply
        run: terraform apply -auto-approve
